# Generated by Django 2.1.4 on 2019-02-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='category',
            new_name='type',
        ),
    ]
