# Generated by Django 2.1.4 on 2019-02-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20190217_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.Restaurant'),
        ),
    ]
