# Generated by Django 2.1.4 on 2019-02-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20190217_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manu',
            name='point',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='point',
        ),
        migrations.AddField(
            model_name='reviews',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
