# Generated by Django 2.1.4 on 2019-02-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_auto_20190220_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='number',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
    ]
