# Generated by Django 2.1.4 on 2019-02-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_restaurant_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='time',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
